apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-dashboard
  name: kubernetes-dashboard-lb
namespace: kubernetes-dashboard
spec:
  selector:
    k8s-app: kubernetes-dashboard
  ports:
    - protocol: TCP
      port: 443 # Adjust port if needed
      targetPort: 8443
  type: LoadBalancer
